### ISSUE TITLE
Update for Magento 2.3.7

### ISSUE THREAD

**Issue by antonfries** [mittwald/magento2-cronjobs#1]
Line 30 and 31 doesn't work in Magento >=2.3.7

The new cron:install only generates one following line in my example installation:

* * * * * /usr/bin/php7.4 /srv/www/magento/standard/2dot3/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule"

**Comment by Hermsi1337** [comment]
closed via #2

**Comment by antonfries** [comment]
Not resolved due to the following code:
`${PHP_BIN} "${INSTALLDIR}/update/cron.php" >> "${INSTALLDIR}/var/log/update.cron.log"`
the update folder does not exist in >=2.3.7 anymore, so please move this section at line 37/38
